#!/bin/sh -e


. /usr/share/debconf/confmodule

db_version 2.0
#db_capb backup
db_capb escape
#db_settitle demo/title


# This implements a simple state machine so the back button can be handled.
STATE=1
while [ "$STATE" != 0 -a "$STATE" != 2 ]; do
        case $STATE in
        1)
                db_input medium ecca-sample-site/servername || true
        ;;
        esac
        
        if db_go; then
                STATE=$(($STATE + 1))
        else
                STATE=$(($STATE - 1))
        fi
#       echo "ON STATE: $STATE"
done

db_stop